R/utils.R
inst/unitTests/runit.utils.R

```r
library(plyr); library(dplyr)
test <- expand.grid.df(expand.grid(site = LETTERS[1:10], visit = 1:3), 
data.frame(year = 2010:2012)) %>% arrange(site, year, visit) %>%
select(year, site, visit)
test <- test %>% mutate(
y  = rpois(nrow(test), lambda = 2),
ocov = rnorm(nrow(test)),
scov = 2 * as.numeric(test$site),
yscov = 1.3 * as.numeric(interaction(test$site, test$year)))
nofac <- formatMult(test)
str(nofac)
test2 <- test %>% mutate(
obsfac = factor(sample(LETTERS[1:2], nrow(test), replace = TRUE)),
sitefac = factor(round_any(as.numeric(site), 5)),
ysfac = factor(round_any(as.numeric(interaction(site, year)), 10))
)
withfac <- formatMult(test2) 
str(withfac)
test3 <- select(test2, -ocov, -scov, -yscov)
onlyfac <- formatMult(test3)
str(onlyfac)
(fm <- colext(~scov, ~1, ~1, ~ocov, …
```

formatMult no longer corrupts covariates when factors are present; fixes #47

---

R/utils.R
inst/unitTests/runit.utils.R

Variables identified within `formatMult` as siteCovs or yearlySiteCovs are now removed from obsCovs prior to `unmarkedMultFrame` object creation; updated unit test as well.

fix failure of formatMult to drop siteCovs and yearlySiteCovs from obsCovs

---

R/utils.R
inst/unitTests/runit.utils.R

Fixed `formatMult` so that input Julian date (JD)/visit chronology information is not converted to factor when it is not, in fact, a factor.  When factor variables are present as additional covariates, the JD/visit chronology variable was coerced to a factor as the intermediate array could only store data with a single mode --- in this case a "character" mode subsequently converted into a factor.  Other non-factor variables are returned to their original mode.  The function now checks the the mode of the JD/visit variable and restores it to its original mode if not a factor.
Unit test updated as well.

Fix formatMult conversion of julian date/visit to factor

---

R/utils.R
inst/unitTests/runit.utils.R

When using `csvToUMF` to convert long data.frames (i.e., `long = TRUE`), the presence of a factor variable resulted in all other variables converting to factors.  This is now fixed (with the caveat noted at the bottom). Additionally, the function now tries to automatically identify and extract site covariates and add them to the `UnmarkedFrameOccu`. 
``` r
library(unmarked)
#> Loading required package: reshape
#> Loading required package: lattice
#> Loading required package: parallel
#> Loading required package: Rcpp
test <- expand.grid.df(expand.grid(site = LETTERS[1:4], julian = c(13, 20, 26)))
test <- test[with(test, order(site, julian)), ]
set.seed(42)
test <- within(test, {
obsfac = factor(sample(LETTERS[1:2], nrow(test), replace = TRUE))
sitefac = factor(round(as.numeric(site)/5)) …
```

formatLong no longer corrupts covariates when factors present; unit test added

---

R/unmarkedFrame.R

Tweaks unmarkedFrame constructor so that obsCovs does not have to have matrix or dataframe as its *first* listed class, as long as it is a matrix or dataframe. If you decide not to do this to avoid a bunch of work accommodating tidyverse objects (I bet this is not the only place where this kind of thing comes up), you might consider including some advice in the documentation that would guide users towards the kind of workaround that I came up with e.g. using as.data.frame() to ensure that data.frame is the only class for the object provided to obsCovs. Closes #111

allow import of dataframes with multiple classes

---

DESCRIPTION
NAMESPACE
R/unmarkedFrame.R
R/utils.R
inst/unitTests/runit.utils.R
man/formatWideLong.Rd

This PR started simply to allow additional arguments to pass through the `formatLong` function to the specified `unmarkedFrame*` constructor functions. It soon became clear, however, that it would be easier to accomplish this by transitioning from older functions in the `reshape` package (e.g., `melt`, `cast`, and `recast`) to their updated versions in the `reshape2` package (e.g., `melt`, `acast`, `dcast`). The two commits in this PR separate those tasks (edit: four commits; I caught a couple of problems in the DESCRIPTION file).
All relevant unit tests have been updated and pass (excepting an unrelated `parboot` test to be fixed in a follow-up PR), and I've added a test comparing a manually created `unmarkedFramePCO` (from the example in the help file) with the corresponding object …

Transition to `reshape2` and allow pass-through arguments to `unmarkedFrame*` constructors if `formatLong`; add addn'l unit tests

---

R/unmarkedFit.R

The likelihood for distsamp exponential/point:
```
point = {
for(j in 1:J) {
int <- integrate(grexp, db[j], db[j+1], rate=rate[i],
stop.on.error=FALSE)
mess <- int$message
if(identical(mess, "OK"))
cp[i, j] <- int$value * 2*pi / a[i,j]
else {
cp[i, j] <- NA
}
}
})
cp[i,] <- cp[i,] * u[i,]
```
In getP the matching chunk looks like this currently:
```
point = {
for(j in 1:J) {
cp[i, j] <- u * integrate(grexp, db[j], db[j+1],
rate=rate[i], rel.tol=1e-4)$value *
2 * pi * a[i, j]
}
})
cp[i,] <- cp[i,] * u[i,]
```
I am guessing they should match? getP and parboot run now but I haven't confirmed the math.

Fix getP for distsamp (potentially fixes #83 and maybe #102)

---

R/gmultmix.R
inst/unitTests/runit.gmultmix.R
man/gmultmix.Rd
src/init.c
src/nll_gmultmix.cpp
src/nll_gmultmix.h
vignettes/cap-recap.Rnw

Adds C++ engine for `gmultmix` and makes it the default. In my tests it's about 8-13x faster than the R engine. It works for both Poisson and negative binomial but only for the two built-in piFun options (removal, double). If the user provides a custom piFun it gives a warning and drops back to the R engine. I think you can use an arbitrary R function in C++ via Rcpp but at that point you probably lose most of the speed advantage, so I didn't try to implement that.
I added tests and also had to update the vignette for gmultmix since it uses a custom piFun.
Here's an R script to benchmark the C engine:
[gmultmix_C_example.txt](https://github.com/rbchan/unmarked/files/2897476/gmultmix_C_example.txt)

Add C engine for gmultmix

---

R/occuRN.R
inst/unitTests/runit.occuRN.R
man/occuRN.Rd
src/init.c
src/nll_occuRN.cpp
src/nll_occuRN.h

Adds C++ engine for `occuRN`. It's about 2x faster than the R engine.  I also added tests for `occuRN` (there didn't seem to be any). Finally, this should fix the NA bug noted in issue #77.
R script to benchmark the C++ engine:
[occuRN_C_example.txt](https://github.com/rbchan/unmarked/files/2897540/occuRN_C_example.txt)

Add C engine for occuRN

---

R/unmarkedFrame.R
inst/unitTests/runit.nonparboot.R

Fixes issue #92 and adds relevant test.

Fix umf subsetting with list when there are no obsCovs (for nonparboot)

---

R/multinomPois.R
inst/unitTests/runit.multinomPois.R
man/multinomPois.Rd
src/init.c
src/nll_multinomPois.cpp
src/nll_multinomPois.h
vignettes/cap-recap.Rnw

Adds C++ engine for `multinomPois` and makes it the default. It's not a lot faster (maybe 30%), but `multinomPois` was already pretty fast (at least for the example datasets). As with `gmultmix` it only supports double/removal piFuns -  if the user provides a custom piFun it gives a warning and drops back to the R engine. I added tests and also had to update the cap-recap vignette since it uses a custom piFun for `multinomPois`.
Here's an R script to benchmark the C engine:
[multinomPois_C_example.txt](https://github.com/rbchan/unmarked/files/2897560/multinomPois_C_example.txt)

Add C engine for multinomPois

---

DESCRIPTION
R/gmultmix.R
R/multinomPois.R
R/piFun.R
R/unmarkedFrame.R
inst/unitTests/runit.pifun.R
man/unmarkedFrameMPois.Rd
man/unmarkedMultFrame.Rd
src/nll_gmultmix.cpp
src/nll_multinomPois.cpp
src/pifun.cpp
src/pifun.h

Add dependent double observer sampling as built-in option for `gmultmix` and `multinomPois`, with `type = 'depDouble'`. 
I also did a little reorganization to split the piFuns out into their own R file (and their own cpp file), to make it more clear they are shared between functions, and to make adding future piFuns easier. Updated the docs to reflect the changes and added relevant tests.
Finally, I corrected a related bug when dealing with missing values in the gmultmix C engine.

Dependent double observer sampling

---

R/unmarkedFrame.R
inst/unitTests/runit.distsamp.r
inst/unitTests/runit.gdistsamp.R

Modification to `unmarkedFrameGDS` that fixes #101. The `unmarkedFrameDS` function already handled this situation.

Throw error when tlength!=nrow(y) in gdistsamp

---

R/gdistsamp.R
inst/unitTests/runit.gdistsamp.R
man/gdistsamp.Rd
src/init.c
src/nll_gdistsamp.cpp
src/nll_gdistsamp.h

Supports all combinations of key function, sampling type, and mixture. I added a bunch of tests to try to cover as many of the combinations as possible.
A possible future CRAN issue is that there are now some C++ compiler warnings apparently as a result of some namespace overlaps between RcppArmadillo and R_ext (used for integration). It does ultimately compile fine though, at least on my computer, and R CMD check is clean.
@rbchan I also found a possible bug in the R engine when there are missing y values. Can you check the commit comment in the patch to see if you agree with the change I made?

C++ engine for gdistsamp

---

R/pcountOpen.R
R/unmarkedFit.R
inst/unitTests/runit.pcountOpen.R

A more complete fix for #110 that correctly simulates data and generates fitted values when `fix='omega'` (omega=1) or `'gamma'` (gamma=0) in `pcountopen`. 
To implement this I had to add a new attribute to `pcountopen` fit objects ("fix") to keep track of which parameter was fixed - guessing from the coefficient names could be problematic. If the attribute is missing (i.e., a model fit from an older version of unmarked is imported) the fix value defaults to "none".

Handle fixed parameters in pcountopen simulate and fitted

---

inst/unitTests/runit.distsamp.r
inst/unitTests/runit.gdistsamp.R
src/detfuns.cpp
src/detfuns.h
src/nll_distsamp.cpp
src/nll_distsamp.h
src/nll_gdistsamp.cpp
src/nll_gdistsamp.h

Addresses #134 by replacing Rdqags with a built-in trapezoidal rule function. It should be extensible to other integrals we need to approximate in the future. This is currently only used for negative exponential (point) and hazard (point and line) for both distsamp and gdistsamp, the other detection functions already used solved integrals in both the C and R code. 
Changing the integral approximation results in some slight differences in parameter estimates for some tests (on order of 1e-4), hence my adjustments to these tests.
No more compiler warnings, at least on my machine!

Use trapezoidal rule instead of Rdqags for approximating integrals

---

DESCRIPTION
NAMESPACE
R/vif.R
inst/unitTests/runit.vif.R
man/vif.Rd

There's been a few questions about calculating variance inflation factors (VIFs) for `unmarked` models on the mailing list. It's fairly easy to do this manually but I figured we could do better. This adds a function to calculate variance inflation factors for parameters in one level of an unmarked model (e.g. `'det'` or `'state'`). I called the function `vif()` to emulate `car::vif()` which I think is the most widely used function for this in R, but I could see changing it to `VIF()`. 
The function subsets the var-covar matrix to a specific model level, converts it to a correlation matrix, and uses that to calculate VIFs the same way `car::vif()` does (see [here](https://github.com/cran/car/blob/764931db4ebe3e80853ff6453f077e045f564584/R/vif.R)). This results in slightly different …

Add function to calculate VIFs

---

DESCRIPTION
NAMESPACE
R/boot.R
R/occuTTD.R
R/ranef.R
R/unmarkedEstimate.R
R/unmarkedFit.R
R/unmarkedFrame.R
inst/unitTests/runit.occuTTD.R
man/fitted-methods.Rd
man/getP-methods.Rd
man/nonparboot-methods.Rd
man/occuTTD.Rd
man/predict-methods.Rd
man/ranef-methods.Rd
man/simulate-methods.Rd
man/unmarkedFit-class.Rd
man/unmarkedFrame-class.Rd
man/unmarkedFrameOccuTTD.Rd
src/init.c
src/nll_occuTTD.cpp
src/nll_occuTTD.h

Adds a new fitting function `occuTTD`, which fits time-to-detection occupancy models (inspired by Jonathan Cohen's recent post on the listserv, https://groups.google.com/forum/#!topic/unmarked/jAkuA0z_aGc).
You can fit models where there is a single survey per site, or multiple surveys per site (e.g., multiple observers). You can also fit dynamic models, with the same interface as `colext`. Time to detection can be modeled with an exponential or Weibull distribution.
Here's an example fitting the  TTD model in AHM, chapter 10:
```r
#AHM Example 10.12.1, page 616-617
library(AHMbook)
library(unmarked)
set.seed(1)
data <- simOccttd()
#Unmarked requires censored values = Tmax
y = data$ttd
y[is.na(y)] <- data$Tmax
sc <- data.frame(covB=data$covB)
oc <- data.frame(covA=data$covA)
umf <- …
```

Fit time-to-detection occupancy models

---

R/boot.R
man/parboot.Rd

Pertains to #149
Adds `ncores` argument to `parboot` and argument/description to docs
Unit tests unchanged but passed
Sorry for the delay, I had LaTeX issues building vignettes...

Add `ncores` option to `parboot`

---

R/occuMS.R
R/occuMulti.R
R/ranef.R
R/unmarkedFrame.R

Fixes #151 and removes a bunch of other instances of `class(.) == *` structure that CRAN discourages. Many still remain especially in `unmarkedFit.R` but are not as urgent. With this patch, the package gets a clean check against R-devel (as long as other patch related to `parboot` #153 is also applied).

Fix broken example and some other `class(.) == *` situations

---

R/boot.R
R/unmarkedFit.R
R/utils.R
inst/unitTests/runit.parboot.R
man/SSE.Rd
man/unmarkedFit-class.Rd

There was an unbound global variable (`availcore`) issue in checks after the last parboot patch #150. I reorganized the parboot code a bit to fix this and removed duplicated code to make future work easier.

Remove duplicated parboot code

---

DESCRIPTION
R/unmarkedFrame.R
man/unmarkedFrameOccuMulti.Rd

Add maxOrder argument to unmarkedFrameOccuMulti, so you can create the frame in a reasonable amount of time if you have a large number of species. Fixes #136.

Add maxOrder argument to unmarkedFrameOccuMulti, fixes #136

---

R/unmarkedFit.R

I updated data.frame prediction methods for unmarkedFit, PCount, OccuFP, ColExt, PCO, and GMM to use the "terms" information based on the original data.  This allows the use of functions like poly() with `raw = FALSE`, `scale()`, and `bs()`, etc., in the formula while getting predictions from new data based on the original transformation instead of a new transformation.
I also ending up adding information on factor levels from the original data to the new model matrix so not all factor levels must be included in the new dataset.  I ran into a problem trying to do this when making predictions based on the first example of `pcount()` in the documentation.
Predict functions for OccuMulti, OccuMS, and OccuTTD use a different approach and I have currently left these untouched.
Different model …

Update prediction methods to allow functions in the formula

---

inst/unitTests/runit.occu.R
inst/unitTests/runit.occuTTD.R

A couple simple tests to confirm the changes @aosmith16 to `predict` are working. I made the assumption that if `scale` in formulas works, then other functions should as well. If that's not necessarily true we may need more tests. I tested only `occu` since the other fitting functions used basically the exact same new code. And finally I added tests to `occuTTD`, which uses the `colext` `predict` method, just to make sure the pass-through trick I was using works with these changes. Along with the other 2 PRs I sent recently (#158, #159), I think we can safely close #29, #115, and #155

A few more tests for fixing predict

---

DESCRIPTION
NAMESPACE
R/getDesign.R
R/unmarkedFrame.R
R/utils.R

`reshape2` doesn't seem to be actively developed anymore, being superseded by `tidyr`. It isn't used much in `unmarked` and where it is used it can be replaced by `stats::reshape`, thus, this PR.
Based on the relevant tests, this change does not reintroduce the issues with factors and `formatLong` fixed in 79870d02. The covariate data frame is re-arranged via indexing rather than melting/casting so there aren't any changes in column classes.
This PR doesn't fix a specific bug and isn't strictly necessary at the moment, but I was looking into #65 and ended up writing it. So feel free not to merge. Either way I think we can close #65.

Remove reshape2 dependency

---

DESCRIPTION
R/colext.R
R/distsamp.R
R/gdistsamp.R
R/gmultmix.R
R/gpcount.R
R/multinomPois.R
R/occu.R
R/occuFP.R
R/occuMS.R
R/occuMulti.R
R/occuRN.R
R/occuTTD.R
R/pcount.R
R/pcount.spHDS.R
R/pcountOpen.R
R/utils.R
inst/unitTests/runit.occu.R
inst/unitTests/runit.utils.R

Returns a matrix of NAs when `se=FALSE` or when Hessian cannot be inverted. Fixes #59.

Use common function for inverting Hessian

---

R/unmarkedFit.R
R/utils.R
inst/unitTests/runit.simulate.R

Unlike other random number generators, `rmultinom` throws errors when dealing with NAs. Added a wrapper around `rmultinom` to use in `simulate` methods, so that it just returns NAs instead:
```r
rmultinom2 <- function(n, size, prob){
if(is.na(size)){
return(matrix(NA, length(prob), length(n)))
}
stats::rmultinom(n=n, size=size, prob=prob)
}
```
Also, and probably more importantly, fixed a major bug in `simulate` for `unmarkedGDS` objects.
Previously:
```r
for(i in 1:M) {
switch(mixture,
P = Ns <- rpois(1, lambda[1]), # lambda[1] for all sites!!!!
NB = {
alpha <- exp(coef(object, type="alpha"))
Ns <- rnbinom(1, mu=lambda[i], size=alpha)
})
```
Now:
```r
for(i in 1:M) {
switch(mixture,
P = Ns <- rpois(1, lambda[i]),
NB = {
alpha <- exp(coef(object, type="alpha"))
Ns <- rnbinom(1, …
```

Fix simulate() to work with multinomial distributions when there are missing values

---

DESCRIPTION
NAMESPACE
R/posteriorSamples.R
R/ranef.R
inst/unitTests/runit.ranef.R
man/posteriorSamples.Rd
man/predict-methods.Rd
man/ranef-methods.Rd

User supplies the `ranef` object and a custom function, and predict returns an estimate, SE, and 95% CI for the function's output parameters. Also adds a `posteriorSamples` function that just grabs the samples, so you can work on them separately. See example below. Fixes #166.
@rbchan, if you could quickly look over the implementation and the docs that would be great since I'm not sure I explained everything correctly.
```r
library(unmarked)
set.seed(4564)
R <- 10
J <- 5
N <- rpois(R, 3)
y <- matrix(NA, R, J)
y[] <- rbinom(R*J, N, 0.5)
K <- 15
umf <- unmarkedFramePCount(y=y)
fm <- pcount(~1 ~1, umf, K=K)
re <- ranef(fm)
#Get posterior samples
(ps <- posteriorSamples(re, nsim=10))
#Custom function that calculates average abundance of sites 1-5 and sites 6-10
myfunc <- function(x){ #x is 10 …
```

Adds predict method for unmarkedRanef class

---

DESCRIPTION

As discussed. Apparently for R 'creator' and 'maintainer' are equivalent so Andy is assigned as `'cre'`. I left out one author (Stefan Theussl) because they were the author of the very first commit (which didn't make sense - maybe Ian copied an existing repository when he started and built off that?). Fixes #173.

Update package authors

---

DESCRIPTION
NAMESPACE
R/occuMulti.R

Moves `parallel` and `Rcpp` from depends to imports (so they no longer need to be explicitly loaded when `unmarked` is), and where possible `unmarked` now uses `importFrom` instead of `imports`. Ideally `lattice` would also be moved out of `depends` but doing so causes issues with some vignettes and examples that are expecting it to be loaded.
These changes make `unmarked` a bit more in line with my understanding of NAMESPACE best practices, but they are not crucial. There are no changes as far as I know to user-facing behavior.

Make namespace more explicit, avoid unnecessarily package loads

---

DESCRIPTION
R/unmarkedFrame.R
R/utils.R
inst/unitTests/runit.unmarkedFrame.R
inst/unitTests/runit.utils.R

This should cover all the `unmarkedFrame` functions and also `csvToUMF`. The new tests cover the basic frame types, but I didn't write separate tests for every individual UMF class. Should fix #179.

Convert characters to factors with warning when building umf

---

DESCRIPTION
R/getDesign.R
inst/unitTests/runit.occuMS.R

Also add `drop=FALSE` in a few places to keep dimensions consistent. Fixes #178.

occuMS: only drop site/observation if the missing covariate is actually used in a formula

---

DESCRIPTION
src/Makevars
src/Makevars.win
src/nll_distsamp.cpp
src/nll_distsamp.h
src/nll_distsampOpen.cpp
src/nll_distsampOpen.h
src/nll_gdistsamp.cpp
src/nll_multmixOpen.cpp
src/nll_multmixOpen.h
src/nll_occu.cpp
src/nll_occu.h
src/nll_occuPEN.cpp
src/nll_occuPEN.h
src/nll_occuRN.cpp
src/nll_pcount.cpp
src/nll_pcountOpen.cpp
src/nll_pcountOpen.h

This PR addresses the issues raised in https://github.com/RcppCore/Rcpp/issues/1158. Rather than define `STRICT_R_HEADERS` in many files I instead added `PKG_CPPFLAGS=-DSTRICT_R_HEADERS` to the `Makevars`. As expected this resulted in immediate failure to compile.
All that was required was to include `float.h` and change instances of `DOUBLE_XMIN` to `DBL_MIN` in a few files. The package checks clean for me now and the tests pass.
Fixes #201

Define STRICT_R_HEADERS and fix resulting problems

---

DESCRIPTION
NAMESPACE
R/boot.R
R/unmarkedCrossVal.R
inst/unitTests/runit.parboot.R
man/parboot.Rd
src/RcppExports.cpp

Use {pbapply} to provide bootstrap and cross-validation progress feedback to user. Ignored if reporting is requested on non-parallel bootstraps. `parboot` units tests modified as necessary and passed. No changes needed for `crossVal` unit tests, but tests passed.

Add progress bar to parametric bootstraps and cross-validations

---

DESCRIPTION
R/predict.R
tests/testthat/test_predict.R

This doesn't add any significant overhead because (1) `terra` is in `suggests` and (2) `raster` (which we already have in `suggests`) now depends on `terra` anyway.

Add support for predicting with terra::rast (SpatRaster) objects as the newdata

---

DESCRIPTION
NEWS.md

As in #263 , the code now requires R>=4.0, so this specifies that requirement in DESCRIPTION, and updates NEWS.md.

Increase required R version to 4.0

---

R/gdistsamp.R
src/RcppExports.cpp
src/nll_gdistsamp.cpp

`kmyt` and `lfac.kmyt` were sent to C++ as arrays, and extracted from using `subcube`. This seems to have caused some instability resulting in unpredictable R crashes. Now `kmyt` and `lfac.kmyt` are sent to C++ as vectors instead.

Refactor gdistsamp likelihood to avoid occasional crashes
